#!/bin/bash

# This script is used to count the maximum number of threads generated by a process.

threadcount=0
end=$((SECONDS+20))

while [ $SECONDS -lt $end ]; do
	temp=`ps -L -o pid= -p 6055 | wc -l`
	if [ $temp -gt $threadcount ]    
	then
		threadcount=$temp	
	fi
done
echo $threadcount
